network:
  address: "127.0.0.1:3223"
  max_connections: 1
  max_message_size: "4KB"
  idle_timeout: 5m
wal:  
  flushing_batch_size: 100
  flushing_batch_timeout: "10ms"
  max_segment_size: "1KB"
  data_directory: "./wal"
  